[toolchain]
anchor_version = "0.31.1"
solana_version = "2.3.8"


[features]
resolution = true
skip-lint = false


[programs.devnet]
dco = "CEHTQCjD4A4z6MYRjXydYvFhnz6s5E5Wha8XvH9xvFXM"
engines = "EhnR4MAU35g4yCnz635ar2BQYec4xXQCPCd76hTFPfDH"
marketplace = "76sgJHKdFqnRQ4sheZzjbNFdqFKvS4akdTbeAhsNB3BA"
nft = "5eMDSRzaq9NUvurN2s5Q2zmCs8cFPaCA2uhz89kSS6pf"
soul_bound = "5HapKjJka6MCGrV3eVC4zkotngCJ25bb16yuea7ucgHd"
zktc = "9kV35dMKi9azmFAiibSUkyMFoZ3QikfE9BV12dN6sgaK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./new_program-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
